name: Test Workflow

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: joanise/test_gha_infra/.github/workflows/level-1.yml@v1.5
